Remove redis cr
IBM/ibm-commonui-operator pull request #178
Opened 2021-01-25 18:50 UTC by Scocconcelli

* Reused finalizer logic to implement the deletion of the Redis CR whenever the operator is removed.

2021-01-25 20:36 UTC, ericabr approved these changes
/lgtm

2021-01-26 14:36 UTC, siddarthpatel commented on pkg/controller/commonwebuiservice/commonwebuiservice_controller.go
> +	finalizerName := "commonui1.operators.ibm.com"
@Scocconcelli Please reuse the `finalizerCr` function that we have to finalize the redis sentinel cr. I see that the only change is in the `finalizerName` so you can pass it as a parameter to the  already present `finalizerCr` function and reuse it.

2021-01-26 14:36 UTC, siddarthpatel requested changes
See comment

2021-01-26 23:56 UTC, ericabr approved these changes
/lgtm

2021-01-26 23:57 UTC, merged